#!/bin/bash
echo "🏗️  Checking Voxanne Services Status"
echo "======================================"
echo ""
echo "✅ FRONTEND (http://localhost:3000)"
curl -s http://localhost:3000 | head -5 > /dev/null 2>&1 && echo "✓ Running" || echo "✗ Not responding"
echo ""
echo "✅ BACKEND (http://localhost:3001)"
curl -s http://localhost:3001/health | jq '.' 2>/dev/null || echo "✗ Not responding"
echo ""
echo "✅ NGROK TUNNEL"
curl -s http://127.0.0.1:4040/api/tunnels 2>/dev/null | jq '.tunnels[0] | {name, public_url}' 2>/dev/null || echo "⏳ Starting up (wait 5s)"
